harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: AWS
deploymentType: AMI
infrastructure:
- type: AWS_AMI
  amiDeploymentType: AWS_ASG
  asgIdentifiesWorkload: false
  autoScalingGroupName: ASG-1
  classicLoadBalancers:
  - Classic-Load-Balancer-1
  cloudProviderName: Cloud Provider 1
  hostNameConvention: ${host.ec2Instance.privateDnsName.split('\.')[0]}
  region: ap-northeast-1
  stageClassicLoadBalancers:
  - Classic-Load-Balancer-1
  stageTargetGroupArns:
  - arn:aws:elasticloadbalancing:ap-northeast-1:456043706209:targetgroup/target-group-1/1a37023a807f7f4e
  targetGroupArns:
  - arn:aws:elasticloadbalancing:ap-northeast-1:456043706209:targetgroup/target-group-1/1a37023a807f7f4e
  useTrafficShift: false
